import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import ContactMeBlock from '../common/components/ContactMeBlock/ContactMeBlock';
import Footer from '../common/components/Footer/Footer';
import Header from '../common/components/Header/Header';
import Icon from '../common/components/Icon/Icon';
import Navbar from '../common/components/Navbar/Navbar';
import PageContent from '../common/components/PageContent/PageContent';
import Presentation from '../common/components/Presentation/Presentation';
import ProjectsList from '../common/components/ProjectsList/ProjectsList';
import { ProjectType } from '../common/types/ProjectType';
import HomepagePicture from '../public/images/me.jpg';
import ProjectPreviewCountriesAPI from '../public/images/projects/REST-Countries-API.png';
import styles from '../styles/pages/Home.module.scss';

const Home: NextPage = () => {
  const projects: ProjectType[] = [
    {
      title: 'REST Countries API with color theme switcher',
      description:
        'Real, organic and arabica. A brand that communicates coffee value.',
      demo: 'https://rest-countries-api-lac.vercel.app/',
      github: 'https://github.com/boutterudy/REST-Countries-API',
      tags: ['React', 'Next.js'],
      preview: (
        <Image
          src={ProjectPreviewCountriesAPI}
          alt='REST Countries API with color theme switcher screenshot'
        />
      ),
      date: new Date(),
      icon: <Icon lib='remix-icon' icon='globe-line' />,
    },
    {
      title: 'REST Countries API with color theme switcher',
      description:
        'Real, organic and arabica. A brand that communicates coffee value.',
      demo: 'https://rest-countries-api-lac.vercel.app/',
      github: 'https://github.com/boutterudy/REST-Countries-API',
      tags: ['React', 'Next.js'],
      preview: (
        <Image
          src={ProjectPreviewCountriesAPI}
          alt='REST Countries API with color theme switcher screenshot'
        />
      ),
      date: new Date(),
      icon: <Icon lib='remix-icon' icon='globe-line' />,
    },
    {
      title: 'REST Countries API with color theme switcher',
      description:
        'Real, organic and arabica. A brand that communicates coffee value.',
      demo: 'https://rest-countries-api-lac.vercel.app/',
      github: 'https://github.com/boutterudy/REST-Countries-API',
      tags: ['React', 'Next.js'],
      preview: (
        <Image
          src={ProjectPreviewCountriesAPI}
          alt='REST Countries API with color theme switcher screenshot'
        />
      ),
      date: new Date(),
      icon: <Icon lib='remix-icon' icon='globe-line' />,
    },
    {
      title: 'REST Countries API with color theme switcher',
      description:
        'Real, organic and arabica. A brand that communicates coffee value.',
      demo: 'https://rest-countries-api-lac.vercel.app/',
      github: 'https://github.com/boutterudy/REST-Countries-API',
      tags: ['React', 'Next.js'],
      preview: (
        <Image
          src={ProjectPreviewCountriesAPI}
          alt='REST Countries API with color theme switcher screenshot'
        />
      ),
      date: new Date(),
      icon: <Icon lib='remix-icon' icon='globe-line' />,
    },
  ];

  return (
    <div>
      <Head>
        <title>Rudy Boutte</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <PageContent>
        <Header>
          <Image
            className={styles.pictureOfMe}
            src={HomepagePicture}
            width={412}
            height={550}
            alt='Rudy Boutte in front of yellow flowers'
          />
        </Header>
        <Presentation />
        <ProjectsList projects={projects} />
        <ContactMeBlock />
      </PageContent>

      <Footer />
    </div>
  );
};

export default Home;
